site_name: Deep-MacroFin Wiki
site_description: 'Deep-MacroFin Wiki'
site_author: 'Rotman Finhub'
site_url: 'https://rotmanfinhub.github.io/deep-macrofin' # the last path should be the same as the reponame for now

copyright: "Rotman Finhub"

# Repository
repo_name: 'GitHub'
repo_url: https://github.com/rotmanfinhub/deep-macrofin" target="_blank

theme:
  name: material
  # custom_dir: mkdocs-material/material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Light Mode

  # 404 page
  static_templates:
    - 404.html

  # Default values, taken from mkdocs_theme.yml
  language: en
  font: false
  # icon:
  #   repo: fontawesome/brands/git-alt
  # favicon: images/favicon.ico
  # logo: images/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.copy

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - assets/css/lightbox.css
  - https://use.fontawesome.com/releases/v6.4.0/css/all.css
  # - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - assets/js/lightbox.js
  # - assets/js/katex.js
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - assets/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - 'Home Page': 'index.md'
  - 'API':
    - 'deep_macrofin.models': 'api/models.md'
    - 'deep_macrofin.evaluations': 'api/evaluations.md'
    - 'deep_macrofin.pde_model': 'api/pde_model.md'
    - 'deep_macrofin.pde_model_time_step': 'api/pde_model_time_step.md'
    - 'deep_macrofin.utils': 'api/utils.md'
  - 'Basic Usage': 
    - 'General Usage': 'usage.md'
    - 'Time Stepping Scheme': 'usage_timestep.md'
    - 'Tips and Additional Considerations': 'faq.md'
  - 'Basic Examples':
    - 'A simple ODE': 'examples/odes/basic_ode1.md'
    - 'Yet another simple ODE': 'examples/odes/basic_ode2.md'
    - 'Second-order ODE': 'examples/odes/second_order.md'
    - 'Cauchy-Euler Equation': 'examples/odes/cauchy-euler.md'
    - 'Discontinuous Function Approximation': 'examples/approx/discont.md'
    - 'Predator-Prey Model': 'examples/odes/predator_prey.md'
    - 'Laplace Equation Dirichlet Problem': 'examples/pdes/laplace.md'
    - 'Time-dependent Heat Equation': 'examples/pdes/heat.md'
    - 'Diffusion Equation': 'examples/pdes/diffusion.md'
  - 'Economic Problems':
    - 'Log Utility': 'examples/macrofinance_models/log_utility.md'
    - '1D Problem': 'examples/macrofinance_models/1d_problem.md'
    - 'PyMacroFin 2D Problem': 'examples/macrofinance_models/pymacrofin_2d_problem.md'
    - 'Di Tella (2017)': 'examples/macrofinance_models/di_tella.md'
    - 'Bewley-Huggett-Aiyagari': 'examples/macrofinance_models/bewley_huggett_aiyagari.md'
    - 'Neoclassical Growth': 'examples/macrofinance_models/neoclassical_growth.md'