name: ci-tests
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [main, master, develop]
  push:
    branches: [develop]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install current package
        run: pip install -e .

      - name: Run tests
        run: pytest tests/
  test-build-package:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Build Package
        run: |
          pip install --upgrade build
          python3 -m build