name: ci-tests
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [main, master, develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install current package
        run: pip install -e .